"""empty message

Revision ID: 1bc2c985c5e7
Revises: 4713f2764c6e
Create Date: 2016-12-17 14:09:42.850754

"""

# revision identifiers, used by Alembic.
revision = '1bc2c985c5e7'
down_revision = '4713f2764c6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply', sa.Column('gender', sa.String(length=8), nullable=True))
    op.add_column('apply', sa.Column('home_address', sa.String(length=400), nullable=True))
    op.add_column('apply', sa.Column('middle_school', sa.String(length=400), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply', 'middle_school')
    op.drop_column('apply', 'home_address')
    op.drop_column('apply', 'gender')
    ### end Alembic commands ###
