"""empty message

Revision ID: 1bc7973bda8a
Revises: 51f5ccfba190
Create Date: 2016-12-10 23:01:57.408047

"""

# revision identifiers, used by Alembic.
revision = '1bc7973bda8a'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('id_card', sa.String(length=200), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('ticket_number', sa.String(length=200), nullable=True),
    sa.Column('apply_profession', sa.String(length=400), nullable=True),
    sa.Column('apply_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apply_mobile', 'apply', ['mobile'], unique=True)
    op.create_index('ix_apply_real_name', 'apply', ['real_name'], unique=False)
    op.create_index('ix_apply_status', 'apply', ['status'], unique=False)
    op.create_index('ix_apply_ticket_number', 'apply', ['ticket_number'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apply_ticket_number', 'apply')
    op.drop_index('ix_apply_status', 'apply')
    op.drop_index('ix_apply_real_name', 'apply')
    op.drop_index('ix_apply_mobile', 'apply')
    op.drop_table('apply')
    ### end Alembic commands ###
