"""empty message

Revision ID: 26e31d214b70
Revises: 1bc2c985c5e7
Create Date: 2016-12-18 22:12:08.445001

"""

# revision identifiers, used by Alembic.
revision = '26e31d214b70'
down_revision = '1bc2c985c5e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply', sa.Column('apply_profession_category', sa.String(length=400), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply', 'apply_profession_category')
    ### end Alembic commands ###
