"""empty message

Revision ID: 4614e13e500b
Revises: 1bc7973bda8a
Create Date: 2016-12-12 17:01:38.536031

"""

# revision identifiers, used by Alembic.
revision = '4614e13e500b'
down_revision = '1bc7973bda8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
