"""empty message

Revision ID: 4713f2764c6e
Revises: 4614e13e500b
Create Date: 2016-12-13 16:57:20.629000

"""

# revision identifiers, used by Alembic.
revision = '4713f2764c6e'
down_revision = '4614e13e500b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
